name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "good morning, good afternoon, good evening, and good night!"

      - name: Print Date
        run: date

      - name: List Files
        run: ls -la
